kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-minecraft
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: minecraft
      port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-editor
spec:
  selector:
    app: {{ .Release.Name }}
  type:  ClusterIP 
  ports:
  - name: {{ .Release.Name }}
    port: 3000
    targetPort: 3000 