apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: minecraft-server
          image: {{ .Values.minecraft.image }}
          env:
          {{- range .Values.minecraft.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: data
              mountPath: /home/minere/minecraft
              subPath: minecraft
        #- name: editor
        #  image: {{ .Values.editor.image }}
        #  command:
        #    [
        #      "/bin/sh",
        #      "-c",
        #      "exec ${OPENVSCODE_SERVER_ROOT}/bin/openvscode-server --host 0.0.0.0 --connection-token {{ .Values.editor.token }} ${@}",
        #      "--",
        #    ]
        #  ports:
        #    - containerPort: 3000
        #      name: http
        #  volumeMounts:        
        #    - name: data
        #      mountPath: /home/workspace
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
